export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 720;
export const CENTER_X = GAME_WIDTH / 2;
export const CENTER_Y = GAME_HEIGHT / 2;
export const HUD_HEIGHT = 60;
export const BOTTOM_HUD_HEIGHT = 170;
export const DIALOG_WIDTH = 1220;
export const DIALOG_HEIGHT = BOTTOM_HUD_HEIGHT;
export const DIALOG_TOP = GAME_HEIGHT - BOTTOM_HUD_HEIGHT;
